name: update go.mod

on:
  workflow_dispatch: {}

jobs:
  update_deps:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.5'
          cache: true
      - run: go get -u
      - run: go mod tidy
      - name: Build
        run: |
          go build
          go build -tags wasmer
          go build -tags wasmtime
          go build -tags docker
          go build -tags wazero
      - name: Test
        run: |
          go test
          go test -tags wasmer
          go test -tags wasmtime
          go test -tags docker
          go test -tags wazero
      - name: git setting
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "546304+github-actions[bot]@users.noreply.github.com"
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update Dependencies
          title: 'auto update dependencies'
          add-paths: |
             go.mod
             go.sum
